### ISSUE TITLE
Require mobx 5 as a peer dep

### ISSUE THREAD

**Issue by stellarhoof** [smartprocure/mobx-autoform#30]
Whenever we deal with observable arrays, our implementation for various functions break. For example, `getPatch` breaks because of `F.simpleDiff`, which doesn't work with MobX 4 arrays, `isDirty` also breaks. Haven't checked any more. Should we require a peer dep of MobX 5?

**Comment by daedalus28** [comment]
We can just be sure to `slice` or call `_.toArray` on arrays there

**Comment by stellarhoof** [comment]
Arrays might be nested, which is why I used `toJS` in https://github.com/smartprocure/mobx-autoform/pull/27/files.

**Comment by stellarhoof** [comment]
Closing as mobx-autoform should really work on both 4 and 5
